### ISSUE TITLE
Stage 2 fails

### ISSUE THREAD

**Issue by akafester** [jac459/neeo2021onward#1]
When I ran the script it failed at stage 2 because the script tried to update pacman.
Pacman was already the correct version so there was no need.

It turns out your script is checking with "pacman --version|grep 'Pacman v'" and that returns
` .--.                  Pacman v5.2.2 - libalpm v12.0.2`

But your script is looking for
`Pacman v5.2.2 - libalpm v12.0.2`

so it keeps failing. Correcting this gets the script running.

**Comment by Ton-O** [comment]
You are right! I was already looking into testing this substring ins-stead of the entire string (don't like to test on .--.) but I will make the proposed change right now.
We can always improve it later.
Thanks for reporting.

**Comment by Ton-O** [comment]
Fix applied, please retest
